// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cascadind_dropdown.EmployeeContext;

#nullable disable

namespace cascadind_dropdown.Migrations
{
    [DbContext(typeof(EContext))]
    [Migration("20240504115617_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cascadind_dropdown.Models.Designation", b =>
                {
                    b.Property<int>("Desig_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Desig_Id"));

                    b.Property<string>("Designation_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Desig_Id");

                    b.ToTable("designation");
                });

            modelBuilder.Entity("cascadind_dropdown.Models.Employee", b =>
                {
                    b.Property<int>("EmpoyeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpoyeeId"));

                    b.Property<int>("DesigId")
                        .HasColumnType("int");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.HasKey("EmpoyeeId");

                    b.HasIndex("DesigId");

                    b.HasIndex("GradeId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("cascadind_dropdown.Models.Grade", b =>
                {
                    b.Property<int>("Grade_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Grade_Id"));

                    b.Property<int>("Desig_Id")
                        .HasColumnType("int");

                    b.Property<string>("Grade_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Grade_Id");

                    b.HasIndex("Desig_Id");

                    b.ToTable("grades");
                });

            modelBuilder.Entity("cascadind_dropdown.Models.Employee", b =>
                {
                    b.HasOne("cascadind_dropdown.Models.Designation", "Designation")
                        .WithMany("Employee")
                        .HasForeignKey("DesigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cascadind_dropdown.Models.Grade", "Grade")
                        .WithMany("Employees")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Designation");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("cascadind_dropdown.Models.Grade", b =>
                {
                    b.HasOne("cascadind_dropdown.Models.Designation", "designation")
                        .WithMany("DesignationGrade")
                        .HasForeignKey("Desig_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("designation");
                });

            modelBuilder.Entity("cascadind_dropdown.Models.Designation", b =>
                {
                    b.Navigation("DesignationGrade");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("cascadind_dropdown.Models.Grade", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
